import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Link, useLocation } from "wouter";
import { ArrowLeft, ArrowRight, Check, FileText, Filter, LibraryBig, MoreHorizontal, Pencil, Plus, Search, ShieldCheck, Trash2, Upload, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { Mark, Logo } from "@/components/OdhyayShell";
import { type StoredPdf, uploadPdf } from "@/lib/pdfUpload";
import { trpc } from "@/lib/trpc";
import { AlertDialog, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

type AdminRecord = { id: number; title: string; slug: string; description: string; coverUrl: string | null; pdfKey: string | null; pdfFilename: string | null; pdfMimeType: string | null; pdfSize: number | null; authorName: string; categoryName: string | null; status: "draft" | "published"; pageCount: number; updatedAt: Date };
type ManagedUser = { id: number; openId: string; name: string | null; email: string | null; loginMethod: string | null; role: "admin" | "user"; lastSignedIn: Date };
type BookDraft = { title: string; authorName: string; categoryName: string; description: string; pageCount: string; coverUrl: string; pdf: StoredPdf | null; status: "draft" | "published" };

const fieldClass = "mt-2 w-full border-b border-[#4a4052] bg-transparent py-2 text-sm text-[#f3eee6] outline-none focus:border-[#b7a4d7]";
const emptyDraft: BookDraft = { title: "", authorName: "", categoryName: "", description: "", pageCount: "", coverUrl: "", pdf: null, status: "published" };

function pdfFromBook(book: AdminRecord): StoredPdf | null {
  return book.pdfKey && book.pdfFilename && book.pdfMimeType === "application/pdf" && book.pdfSize ? { key: book.pdfKey, filename: book.pdfFilename, mimeType: "application/pdf", size: book.pdfSize } : null;
}

function AdminGate({ children }: { children: ReactNode }) {
  const { user, loading } = useAuth();
  if (loading) return <div className="min-h-screen bg-[#111015] p-10 text-sm text-[#8f8996]">Preparing your workspace…</div>;
  if (!user || user.role !== "admin") return <div className="flex min-h-screen items-center justify-center bg-[#111015] p-6 text-[#f3eee6]"><div className="max-w-md border hairline bg-[#151219] p-8 text-center"><Mark /><h1 className="font-display mt-5 text-3xl">Private workspace</h1><p className="mt-4 text-sm leading-7 text-[#958d9b]">Please sign in with an administrator account to manage the ODHYAY library.</p><Link href="/" className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-amethyst">Return to library <ArrowRight size={14} /></Link></div></div>;
  return <>{children}</>;
}

function AdminSidebar({ active }: { active: "Overview" | "Books" | "Access" }) {
  const [, navigate] = useLocation();
  const links = [{ label: "Overview" as const, href: "/admin", icon: LibraryBig }, { label: "Books" as const, href: "/admin/books", icon: FileText }, { label: "Access" as const, href: "/admin/access", icon: UsersRound }];
  return <aside className="hidden w-64 shrink-0 border-r hairline bg-[#151219] p-6 lg:block"><Logo /><p className="eyebrow mt-14 text-[#777080]">Workspace</p><nav className="mt-5 flex flex-col gap-1">{links.map(({ label, href, icon: Icon }) => <button key={href} onClick={() => navigate(href)} className={`focus-ring flex items-center gap-3 px-3 py-3 text-left text-sm transition ${active === label ? "bg-[#2c2534] text-amethyst" : "text-[#9b93a1] hover:text-[#f3eee6]"}`}><Icon size={16} />{label}</button>)}</nav><div className="mt-auto pt-16"><Link href="/" className="focus-ring flex items-center gap-2 text-xs font-semibold text-[#817989] hover:text-[#f3eee6]"><ArrowLeft size={14} /> Exit workspace</Link></div></aside>;
}

function AdminShell({ children, active }: { children: ReactNode; active: "Overview" | "Books" | "Access" }) {
  return <AdminGate><div className="flex min-h-screen bg-[#111015] text-[#f3eee6]"><AdminSidebar active={active} /><div className="min-w-0 flex-1"><header className="flex h-[76px] items-center justify-between border-b hairline px-5 md:px-10"><div className="flex items-center gap-3 lg:hidden"><Mark small /><span className="font-display tracking-[.14em]">ODHYAY</span></div><div className="hidden text-xs font-semibold text-[#8f8996] lg:block">Admin workspace <span className="mx-2 text-[#51485b]">/</span> {active}</div><div className="flex items-center gap-3 text-xs text-[#8f8996]"><ShieldCheck size={15} className="text-amethyst" /> Private access</div></header><main className="p-5 md:p-10">{children}</main></div></div></AdminGate>;
}

function PdfUploadField({ pdf, onChange }: { pdf: StoredPdf | null; onChange: (pdf: StoredPdf | null) => void }) {
  const [uploading, setUploading] = useState(false);
  const choose = async (file: File | undefined) => {
    if (!file) return;
    setUploading(true);
    try { onChange(await uploadPdf(file)); toast.success("PDF stored securely."); }
    catch (error) { toast.error(error instanceof Error ? error.message : "PDF upload could not be completed."); }
    finally { setUploading(false); }
  };
  return <section className="border border-dashed border-[#5a4e66] bg-[#111015] p-4"><p className="eyebrow text-[#817989]">Reader PDF</p><p className="mt-2 text-xs leading-5 text-[#8f8996]">Upload one PDF up to 30 MB. It is stored through the managed document service and attaches when you save the book.</p>{pdf ? <div className="mt-4 flex items-center justify-between gap-3 border-t border-[#332d39] pt-3"><div className="min-w-0"><p className="truncate text-xs font-semibold text-[#ded6e0]">{pdf.filename}</p><p className="mt-1 text-[.65rem] text-[#817989]">{Math.ceil(pdf.size / 1024)} KB · Stored PDF</p></div><button type="button" onClick={() => onChange(null)} className="focus-ring text-xs text-[#d5a6ad]">Remove</button></div> : <label className="focus-ring mt-4 inline-flex cursor-pointer items-center gap-2 border border-[#4a4052] px-3 py-2 text-xs font-semibold text-[#d9d0df] hover:border-amethyst"><Upload size={14} />{uploading ? "Uploading…" : "Choose PDF"}<input type="file" accept="application/pdf,.pdf" className="sr-only" disabled={uploading} onChange={event => void choose(event.target.files?.[0])} /></label>}</section>;
}

function BookFields({ draft, onChange, showPdf = true }: { draft: BookDraft; onChange: (draft: BookDraft) => void; showPdf?: boolean }) {
  const change = <K extends keyof BookDraft>(key: K, value: BookDraft[K]) => onChange({ ...draft, [key]: value });
  return <div className="space-y-5"><label className="block"><span className="eyebrow text-[#817989]">Title</span><input required value={draft.title} onChange={event => change("title", event.target.value)} className={`${fieldClass} text-lg`} /></label><div className="grid gap-5 sm:grid-cols-2"><label><span className="eyebrow text-[#817989]">Author</span><input required value={draft.authorName} onChange={event => change("authorName", event.target.value)} className={fieldClass} /></label><label><span className="eyebrow text-[#817989]">Category</span><input required value={draft.categoryName} onChange={event => change("categoryName", event.target.value)} className={fieldClass} /></label></div><label className="block"><span className="eyebrow text-[#817989]">Description</span><textarea required rows={4} value={draft.description} onChange={event => change("description", event.target.value)} className="mt-2 w-full border border-[#4a4052] bg-[#111015] p-3 text-sm text-[#f3eee6] outline-none focus:border-[#b7a4d7]" /></label><div className="grid gap-5 sm:grid-cols-2"><label><span className="eyebrow text-[#817989]">Pages</span><input type="number" min="0" value={draft.pageCount} onChange={event => change("pageCount", event.target.value)} className={fieldClass} /></label><label><span className="eyebrow text-[#817989]">Cover URL</span><input value={draft.coverUrl} onChange={event => change("coverUrl", event.target.value)} className={fieldClass} placeholder="https://…" /></label></div>{showPdf && <PdfUploadField pdf={draft.pdf} onChange={pdf => change("pdf", pdf)} />}<label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={draft.status === "published"} onChange={event => change("status", event.target.checked ? "published" : "draft")} /> Publish to readers</label></div>;
}

function bookPayload(draft: BookDraft) {
  return { title: draft.title, authorName: draft.authorName, categoryName: draft.categoryName, description: draft.description, pageCount: Number(draft.pageCount || 0), coverUrl: draft.coverUrl || undefined, status: draft.status, ...(draft.pdf ? { pdfKey: draft.pdf.key, pdfFilename: draft.pdf.filename, pdfMimeType: draft.pdf.mimeType, pdfSize: draft.pdf.size } : {}) };
}

function invalidateBookViews(utils: ReturnType<typeof trpc.useUtils>) { return Promise.all([utils.admin.listBooks.invalidate(), utils.library.list.invalidate(), utils.library.categories.invalidate(), utils.library.getBySlug.invalidate()]); }

function EditBookDialog({ book, open, onOpenChange }: { book: AdminRecord; open: boolean; onOpenChange: (open: boolean) => void }) {
  const utils = trpc.useUtils();
  const [draft, setDraft] = useState<BookDraft>({ title: book.title, authorName: book.authorName, categoryName: book.categoryName ?? "", description: book.description, pageCount: String(book.pageCount), coverUrl: book.coverUrl ?? "", pdf: pdfFromBook(book), status: book.status });
  useEffect(() => { if (open) setDraft({ title: book.title, authorName: book.authorName, categoryName: book.categoryName ?? "", description: book.description, pageCount: String(book.pageCount), coverUrl: book.coverUrl ?? "", pdf: pdfFromBook(book), status: book.status }); }, [book.id, open]);
  const update = trpc.admin.updateBook.useMutation({ onSuccess: async () => { await invalidateBookViews(utils); onOpenChange(false); toast.success("Book updated."); }, onError: error => toast.error(error.message || "The book could not be updated.") });
  const submit = (event: FormEvent) => { event.preventDefault(); update.mutate({ id: book.id, ...bookPayload(draft), ...(draft.pdf ? {} : { pdfKey: null, pdfFilename: null, pdfMimeType: null, pdfSize: null }) }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto bg-[#151219] text-[#f3eee6] sm:max-w-2xl"><DialogHeader><DialogTitle className="font-display text-3xl">Edit book.</DialogTitle><DialogDescription className="text-[#8f8996]">Changes update the persistent reader library.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><BookFields draft={draft} onChange={setDraft} /><DialogFooter><button type="button" onClick={() => onOpenChange(false)} className="px-4 py-2 text-sm text-[#b8afbd]">Cancel</button><button disabled={update.isPending} className="bg-[#b7a4d7] px-4 py-2 text-sm font-semibold text-[#17121c] disabled:opacity-50">{update.isPending ? "Saving…" : "Save changes"}</button></DialogFooter></form></DialogContent></Dialog>;
}

function BookActions({ book }: { book: AdminRecord }) {
  const utils = trpc.useUtils(); const [editing, setEditing] = useState(false); const [confirmDelete, setConfirmDelete] = useState(false);
  const remove = trpc.admin.deleteBook.useMutation({ onSuccess: async () => { await invalidateBookViews(utils); setConfirmDelete(false); toast.success("Book deleted."); }, onError: error => toast.error(error.message || "The book could not be deleted.") });
  return <><DropdownMenu><DropdownMenuTrigger asChild><button className="focus-ring rounded p-2 text-[#817989] hover:text-[#f3eee6]" aria-label={`Manage ${book.title}`}><MoreHorizontal size={17} /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => setEditing(true)}><Pencil /> Edit book</DropdownMenuItem><DropdownMenuItem variant="destructive" onSelect={() => setConfirmDelete(true)}><Trash2 /> Delete book</DropdownMenuItem></DropdownMenuContent></DropdownMenu><EditBookDialog book={book} open={editing} onOpenChange={setEditing} /><AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}><AlertDialogContent className="bg-[#151219] text-[#f3eee6]"><AlertDialogHeader><AlertDialogTitle>Delete “{book.title}”?</AlertDialogTitle><AlertDialogDescription className="text-[#8f8996]">This removes the book and its associated reader progress, favorites, and bookmarks. This cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><button type="button" disabled={remove.isPending} onClick={() => remove.mutate({ id: book.id })} className="bg-red-700 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{remove.isPending ? "Deleting…" : "Delete book"}</button></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

function AdminEmpty() { return <div className="border border-dashed border-[#4a4052] px-6 py-14 text-center"><Mark /><h2 className="font-display mt-5 text-3xl">The shelf is clear.</h2><p className="mt-3 text-sm text-[#8f8996]">Add the first book to begin building the library.</p><Link href="/admin/books/new" className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-amethyst">Add a book <ArrowRight size={14} /></Link></div>; }

export function AdminPersistentDashboardPage() {
  const { user } = useAuth(); const records = trpc.admin.listBooks.useQuery(undefined, { enabled: user?.role === "admin" }); const items = (records.data ?? []) as AdminRecord[]; const published = items.filter(item => item.status === "published").length; const categories = new Set(items.map(item => item.categoryName).filter(Boolean)).size;
  return <AdminShell active="Overview"><div className="mx-auto max-w-[1120px]"><div className="flex flex-col justify-between gap-6 border-b hairline pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow text-amethyst">Overview</p><h1 className="font-display mt-4 text-5xl">The shelf, now.</h1><p className="mt-3 text-sm text-[#8f8996]">A clear view of your persisted library.</p></div><Link href="/admin/books/new" className="focus-ring inline-flex w-fit items-center gap-2 bg-[#b7a4d7] px-4 py-3 text-xs font-bold uppercase tracking-[.14em] text-[#17121c]"><Plus size={15} /> Add a book</Link></div><div className="mt-8 grid gap-px border hairline bg-[#332d39] sm:grid-cols-3">{[["Total books", String(items.length)], ["Published", String(published)], ["Categories", String(categories)]].map(([label, value]) => <div key={label} className="bg-[#151219] p-6"><p className="text-xs text-[#837b8b]">{label}</p><p className="mt-4 font-display text-4xl text-[#eee8ef]">{value}</p><p className="mt-3 text-[.64rem] font-bold uppercase tracking-[.12em] text-[#b7a4d7]">Persisted data</p></div>)}</div></div></AdminShell>;
}

export function AdminPersistentBooksPage() {
  const { user } = useAuth(); const records = trpc.admin.listBooks.useQuery(undefined, { enabled: user?.role === "admin" }); const items = (records.data ?? []) as AdminRecord[];
  return <AdminShell active="Books"><div className="mx-auto max-w-[1120px]"><div className="flex flex-col justify-between gap-5 border-b hairline pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow text-amethyst">Content / 01</p><h1 className="font-display mt-4 text-5xl">Your books.</h1></div><Link href="/admin/books/new" className="focus-ring inline-flex w-fit items-center gap-2 bg-[#b7a4d7] px-4 py-3 text-xs font-bold uppercase tracking-[.14em] text-[#17121c]"><Plus size={15} /> Add a book</Link></div><div className="mt-8 flex items-center justify-between border-b hairline pb-4"><div className="flex items-center gap-3 text-xs text-[#8f8996]"><Search size={15} /><span>{items.length} persisted books</span></div><span className="flex items-center gap-2 text-xs text-[#8f8996]"><Filter size={14} /> All records</span></div>{records.isLoading ? <p className="py-12 text-sm text-[#8f8996]">Loading book records…</p> : items.length ? <div className="mt-2 overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="border-b hairline text-[.62rem] font-bold uppercase tracking-[.15em] text-[#716978]"><th className="py-4">Book</th><th className="py-4">Author</th><th className="py-4">Category</th><th className="py-4">Status</th><th className="py-4">Pages</th><th /></tr></thead><tbody>{items.map(book => <tr key={book.id} className="border-b hairline text-sm"><td className="py-4"><div className="flex items-center gap-4"><div className="flex h-12 w-9 items-center justify-center bg-[#27212d] text-amethyst"><FileText size={14} /></div><span className="text-[#e1d9e2]">{book.title}</span></div></td><td className="py-4 text-[#98909f]">{book.authorName}</td><td className="py-4 text-[#98909f]">{book.categoryName ?? "—"}</td><td className="py-4"><span className={book.status === "published" ? "text-[#82b49b]" : "text-[#cda66c]"}>{book.status}</span></td><td className="py-4 text-[#777080]">{book.pageCount || "—"}</td><td className="py-4 text-right"><BookActions book={book} /></td></tr>)}</tbody></table></div> : <div className="mt-8"><AdminEmpty /></div>}</div></AdminShell>;
}

export function AdminPersistentNewBookPage() {
  const [, navigate] = useLocation(); const utils = trpc.useUtils(); const [draft, setDraft] = useState<BookDraft>(emptyDraft);
  const create = trpc.admin.createBook.useMutation({ onSuccess: async () => { await invalidateBookViews(utils); toast.success("Book saved to the database."); navigate("/admin/books"); }, onError: error => toast.error(error.message || "The book could not be saved.") });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate(bookPayload(draft)); };
  return <AdminShell active="Books"><div className="mx-auto max-w-[760px]"><Link href="/admin/books" className="focus-ring inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.14em] text-[#8f8996]"><ArrowLeft size={15} /> Books</Link><div className="mt-10 border-b hairline pb-8"><p className="eyebrow text-amethyst">Content / 02</p><h1 className="font-display mt-4 text-5xl">Add a book.</h1><p className="mt-3 text-sm text-[#8f8996]">Add the information once. The record persists for every reader.</p></div><form onSubmit={submit} className="mt-10 space-y-8"><BookFields draft={draft} onChange={setDraft} /><button disabled={create.isPending} className="focus-ring inline-flex items-center gap-3 bg-[#b7a4d7] px-5 py-3 text-xs font-bold uppercase tracking-[.15em] text-[#17121c] disabled:opacity-50">{create.isPending ? "Saving…" : <><Check size={15} /> Save book</>}</button></form></div></AdminShell>;
}

export function AdminPersistentAccessPage() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const users = trpc.admin.listUsers.useQuery(undefined, { enabled: user?.role === "admin" }); const setRole = trpc.admin.setUserRole.useMutation({ onSuccess: async () => { await utils.admin.listUsers.invalidate(); toast.success("Access role updated."); }, onError: error => toast.error(error.message || "Access role could not be updated.") }); const people = (users.data ?? []) as ManagedUser[];
  return <AdminShell active="Access"><div className="mx-auto max-w-[1120px]"><div className="border-b hairline pb-8"><p className="eyebrow text-amethyst">Access / 03</p><h1 className="font-display mt-4 text-5xl">People, carefully.</h1><p className="mt-3 max-w-xl text-sm leading-7 text-[#8f8996]">Google readers appear here after their first sign-in. Administrators can grant library-management access to an intended account.</p></div><div className="mt-8 overflow-x-auto border hairline bg-[#151219]"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b hairline text-[.62rem] font-bold uppercase tracking-[.15em] text-[#716978]"><th className="px-5 py-4">Reader</th><th className="px-5 py-4">Provider</th><th className="px-5 py-4">Last seen</th><th className="px-5 py-4">Role</th><th className="px-5 py-4 text-right">Action</th></tr></thead><tbody>{users.isLoading ? <tr><td colSpan={5} className="px-5 py-10 text-sm text-[#8f8996]">Loading access records…</td></tr> : people.map(person => <tr key={person.openId} className="border-b hairline text-sm last:border-0"><td className="px-5 py-4"><p className="font-medium text-[#e7dfe9]">{person.name || person.email || "Unnamed reader"}</p><p className="mt-1 max-w-[280px] truncate text-xs text-[#817989]">{person.email || person.openId}</p></td><td className="px-5 py-4 text-[#98909f]">{person.loginMethod || "session"}</td><td className="px-5 py-4 text-[#98909f]">{new Date(person.lastSignedIn).toLocaleDateString()}</td><td className="px-5 py-4"><span className={person.role === "admin" ? "text-amethyst" : "text-[#98909f]"}>{person.role}</span></td><td className="px-5 py-4 text-right"><button disabled={setRole.isPending || person.openId === user?.openId} onClick={() => setRole.mutate({ openId: person.openId, role: person.role === "admin" ? "user" : "admin" })} className="focus-ring border border-[#4a4052] px-3 py-2 text-[.65rem] font-bold uppercase tracking-[.12em] text-[#d9d0df] transition hover:border-amethyst hover:text-amethyst disabled:cursor-not-allowed disabled:opacity-40">{person.openId === user?.openId ? "Current admin" : person.role === "admin" ? "Make reader" : "Make admin"}</button></td></tr>)}</tbody></table></div></div></AdminShell>;
}
